export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
export const GET_COUNTER = 'GET_COUNTER'

export const GET_GAME_ITEMS = "GET_GAME_ITEMS"
export const SET_GAME_ITEMS = "SET_GAME_ITEMS"

export const GET_GAME_ITEM_DETAIL = "GET_GAME_ITEMS_DETAIL"
